from enum import Enum


class MSG_FROM_MIRROR_KEYS(Enum):
    MIRROR_READY = 1
    MIRROR_TRACKING_STARTED = 2
    MIRROR_TRACKING_DATA = 3
    MIRROR_TRACKING_LOST = 4


class MSG_TO_MIRROR_KEYS(Enum):
    STATIC_TEXT = 1
    DYNAMIC_TEXT = 2
    RENDER_SKELETON = 3
    CLEAR_SKELETON = 4


class STATIC_TEXT_POSITIONS(Enum):
    CENTER = 1
    TOP_LEFT = 2
    TOP_RIGHT = 3
    BOTTOM_LEFT = 4
    BOTTOM_RIGHT = 5
